spring:
  profiles:
    active: test
#   active: prod

  http:
  multipart:
  maxFileSize: 2MB

server:
  port: 8888

mybatis:
  config-location: classpath:mybatis/mapper/mybatis-config.xml

logging:
  level:
    com.scan.keeper.mapper: debug
